// Style objects
export const styles = {
    container: {
      bg: "purpleDark",
      color: "lavenderLight",
      p: "2.5rem",
      borderBottomLeftRadius: "md",
      borderBottomRightRadius: "md",
      h: { base: "100%", md: "37.375rem" },
      display: "flex",
      flexDirection: "column",
      alignItems: "start",
    },
    contentWrapper: {
      mt: "2.5rem",
      display: "flex",
      gap: "0 1.5rem",
      flexDirection: "column",
    },
    heading: {
      fontSize: { base: "base.2xl", md: "base.display" },
      lineHeight: "display",
      letterSpacing: "tight",
      fontWeight: "medium",
    },
    highlightedText: {
      fontWeight: "light",
      fontStyle: "italic",
      bgGradient: "secondary",
      bgClip: "text",
      color: "transparent",
      pr: "1rem",
      fontFamily: "Georgia, serif",
    },
    subtitle: {
      fontSize: "base.subtitle",
      lineHeight: "base",
      mt: "1.5rem",
    },
    footer: {
      mt: "auto",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "end",
      width: "100%",
    },
    availabilityText: {
      fontSize: "base.small",
      lineHeight: "snug",
      fontWeight: "medium",
    },
    scrollImage: {
      userSelect: "none",
    },
    servicesGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "2.5rem",
      p: "2.5rem 0rem",
    },
    serviceCard: {
      display: "flex",
      flexDirection: "column",
      gap: "1.5rem",
      bgGradient: "secondary",
      p: "2.25rem",
      borderRadius: "md",
      h: "21.613rem",
    },
    serviceTitle: {
      fontSize: "base.title",
      lineHeight: "title",
      letterSpacing: "tight",
    },
    serviceDescription: {
      fontSize: "base.small",
      lineHeight: "snug",
      mt: "1.5rem",
    },
    lightPatternSection: {
      backgroundImage: `url(./assets/bg-pattern-light.png)`,
      w: "100%",
      backgroundSize: "cover",
      backgroundPosition: "center",
      color: "lavenderLight",
      p: "2.5rem 0rem",
      borderRadius: "md",
      h: "37.5rem",
    },
    darkPatternSection: {
      backgroundImage: `url(./assets/bg-pattern-dark.png)`,
      w: "100%",
      backgroundSize: "cover",
      backgroundPosition: "center",
      color: "lavenderLight",
      p: "2.5rem 0rem",
      borderRadius: "md",
      h: "37.5rem",
      mt: "2.5rem",
    },
  };